PAD_TOKEN = 0
SOS_TOKEN = 1
EOS_TOKEN = 2
ALP_TOKEN = 3

LR = 0.05
NUM_LAYERS = 2
MAX_LENGTH = 15
LATENT_SIZE = 32
VOCABULARY_SIZE = 29
CONDITION_CATEGORY = 4
CONDITION_EMBEDDING_SIZE = 8
BIDIRECTIONAL = True
